# Generated by Django 3.2 on 2022-01-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='type',
            new_name='product_type',
        ),
    ]
