# Generated by Django 3.2 on 2022-01-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productreview_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='productreview',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
