# Generated by Django 3.2 on 2022-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numberofratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalrating',
            field=models.IntegerField(default=0),
        ),
    ]
